sudo:   required

services:
        - docker

before_install:
        - docker build -t fakharu/docker-react -f Dockerfile.dev .

script:
        - docker run fakharu/docker-react npm run test -- --coverage
